### ISSUE TITLE
Hidden elements causing incorrect watermark display - a solution

### ISSUE THREAD

**Issue by moggoly** [marioestrada/jQuery-Watermark#1]
Been fighting with this one for some time, and have finally found the cause and a solution.

In my case, I have watermarked fields that are inside a hidden jQueryUI accordion page. When the accordion page is shown, the watermark does not look right - it is not the correct height.

The problem comes down entirely to the way in which .outerHeight() is implemented in jQuery. It does not return the correct height for hidden elements, or elements which are contained within a hidden element.

Solution - I have successfully used a plugin which correctly obtains the outerHeight value of the element. It does this by removing the hidden / visible / etc attributes of the element in question, obtaining the correct value, then restoring all the attributes to their original settings. This plugin can be found here: http://dreamerslab.com/blog/en/get-hidden-elements-width-and-height-with-jquery/

Change this [line 92]:

e_height = $elem.outerHeight();

to this:

e_height = $elem.actual('outerHeight');

after including the jquery.actual.js plugin file. It might be worth including a small implementation of the same algorithm inside the watermark plugin to remove the dependency.

**Comment by marioestrada** [comment]
What version of jquery are you using? Yes outerHeight has that
limitation, it maybe fixed on a recent release of jquery but I'm not
sure.

On Tuesday, July 5, 2011, moggoly
reply@reply.github.com
wrote:

> Been fighting with this one for some time, and have finally found the cause and a solution.
> 
> In my case, I have watermarked fields that are inside a hidden jQueryUI accordion page. When the accordion page is shown, the watermark does not look right - it is not the correct height.
> 
> The problem comes down entirely to the way in which .outerHeight() is implemented in jQuery. It does not return the correct height for hidden elements, or elements which are contained within a hidden element.
> 
> Solution - I have successfully used a plugin which correctly obtains the outerHeight value of the element. It does this by removing the hidden / visible / etc attributes of the element in question, obtaining the correct value, then restoring all the attributes to their original settings. This plugin can be found here: http://dreamerslab.com/blog/en/get-hidden-elements-width-and-height-with-jquery/
> 
> Change this [line 92]:
> 
> e_height = $elem.outerHeight();
> 
> to this:
> 
> e_height = $elem.actual('outerHeight');
> 
> after including the jquery.actual.js plugin file. It might be worth including a small implementation of the same algorithm inside the watermark plugin to remove the dependency.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/marioestrada/jQuery-Watermark/issues/1

## 

[image: mario.ec] http://mario.ec/

_Mario Estrada_ » http://mario.ec/

(593) 9-362-3535
me@mario.ec | http://mario.ec
@marioeg http://twitter.com/marioeg

**Comment by moggoly** [comment]
Using jQuery 1.6.2

**Comment by marioestrada** [comment]
This is a known issue with jQuery and hidden elements the only workaround is depending on an external plugin and I think you found the workaround. I don't plan to depend on an external plugin I may look for other solutions though.

Thanks.

**Comment by davispw** [comment]
What's the status of this other proposed fix?

https://github.com/marioestrada/jQuery-Watermark/pull/3

In my opinion the issue should not be closed just because the proposal (using external plugin) is not acceptable.  It is still a real issue!

**Comment by marioestrada** [comment]
Yes it is an issue, but as you can see using a plugin to fix it is not hard and anyone can do it. I wan't the plugin to be as simple as possible. I might look into fixing this without a plugin when I have some time.
