### ISSUE TITLE
 No option for on-focus color

### ISSUE THREAD

**Issue by celtric** [marioestrada/jQuery-Watermark#2]
I'm having a problem with a field which has a black background when not focused, and a white one when focused, as I cannot change the watermark color.

It would be nice to add a `focusColor` option in `css_options`, and also a class to the watermark (`.watermark` when not focused, `.watermark.active` when focused).

BTW, thank you for the plugin :)

**Comment by marioestrada** [comment]
You can add that functionality with jQuery though:

``` Javascript
$('input').focus(function(){
  $(this).siblings('.watermark').addClass('active');
}).blur(function()
{
  $(this).siblings('.watermark').removeClass('active');
});
```

Or something like that, I haven't really tested it.

**Comment by celtric** [comment]
I feel seriously stupid now.

Thanks for your reply, can't think of a simpler way to do it :)
