### ISSUE TITLE
Autofill issue

### ISSUE THREAD

**Issue by Tetriz** [marioestrada/jQuery-Watermark#4]
Hi, this is the known issue described here: https://github.com/marioestrada/jQuery-Watermark/wiki/Instructions

There is a solution provided. But as you wrote "it is not a very good one". Are you going to provide a more solid solution in the main branch?

**Comment by marioestrada** [comment]
This is a browser issue, and a fix would involve an inefficient mess. I encourage you to find a solution based on the one I provided that applies to your specific form, since that would be the best way to address the issue.

I haven't found a fix for every case, sorry.
