### ISSUE TITLE
When loaded in <head>, doesn't mark up .jq_watermark elements

### ISSUE THREAD

**Issue by matthias-b** [marioestrada/jQuery-Watermark#7]
When the script is loaded as a <script> element in <head>, the statement 

$('.jq_watermark').watermark();

has no effect on elements with class jq_watermark, as the page has not yet loaded.

If this is instead called on document.ready, it works both inline and in <head>.

jQuery(function() { $('.jq_watermark').watermark(); });

**Comment by matthias-b** [comment]
Sorry, can't get the github markdown working correctly.

**Comment by marioestrada** [comment]
Should be fixed now, download latest version.
