### ISSUE TITLE
Input box gets resized after applying widget

### ISSUE THREAD

**Issue by jkeath** [marioestrada/jQuery-Watermark#8]
What steps will reproduce the problem?
1.apply the widget to any input box that width and height are set higher than normal or default. so ex I set my width to 668 and my height to 21.
2.notice that the input box is now resized to like 132px width and 13px height

What is the expected output? What do you see instead?
The input box should not be resized.

What version of the product are you using? On what operating system?
Version 1.3

Please provide any additional information below.
The offending code is line 83.  

$elem.wrap(watermark_container).attr('data-jq-watermark', 'processed');

The .wrap() function used in a way it was not intended and the side affect is that the input box size gets reset.  I would suggest just setting the attr without the wrap statement. Like so.  This fixes the issue and still gives the input the desired data attribute.
$elem.attr('data-jq-watermark', 'processed');

**Comment by marioestrada** [comment]
You don't need a jsfiddle account to create one, please if you have the time post an example.

**Comment by jkeath** [comment]
Here is the fiddle example.
It doesn't work at all in IE on fiddle, not sure why as I'm using IE for work and it works fine.  Must be something in fiddle, but look at it in FF or Chrome on the fiddle link and you can see the working example.

http://jsfiddle.net/HfAh3/1/

**Comment by marioestrada** [comment]
I see, you are setting a width with percentages, I added a fix for this in the latest release just add an attribute `data-percent-width="true"` to the input html and it should work.

See http://jsfiddle.net/HfAh3/2/

**Comment by jkeath** [comment]
Ahh okay well I suppose I can do that.  Just curious though, the wrap is causing the issue and there is no need to use .wrap() wouldn't it make better sense to simply change that code as I suggested then the users don't need to tac on another data attribute to their inputs?

**Comment by jkeath** [comment]
Wait, the height is still getting messed up so your fix does fix the width but not the height getting changed.  

Here is an updated example.
http://jsfiddle.net/HfAh3/14/

SOrry forgot to add that attr ...so here is the working example

http://jsfiddle.net/HfAh3/15/

**Comment by jkeath** [comment]
FYI..this is a really great plugin and gives us exactly what we need.  Just this one issue.  Thanks for your contribution to the community.

**Comment by marioestrada** [comment]
Yeah it looks like it's not working with the height, if your code changes work please fork this repository and issue a pull request so I can test it and merge it with the code.

**Comment by marioestrada** [comment]
Right now I don't have the time to implement and test the changes you sent, if you can't issue a pull request I'll look into this issue when I have some spare time in my hands :)

**Comment by jkeath** [comment]
How do I issue a pull request?  Sorry I'm new to github.

**Comment by marioestrada** [comment]
Fork this repository, commit the code changes using git then browser to your repository and issue a pull request with your commits.

Take a look at http://help.github.com/send-pull-requests/ if you need more help.

**Comment by jkeath** [comment]
I'm having trouble getting cloned from work, I'll do this tonight at home.  I'll branch and do a pull request.

**Comment by jkeath** [comment]
okay I figured out my issues with GIT and I was able to do what you asked.  I think I did it correctly.  I forked, then branched then modified and then put through a pull request.

**Comment by jkeath** [comment]
FYI.. I didn't apply the fix to the minimfied file..just the normal one
